### ISSUE TITLE
CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Wangwang99999** [roboflow/rf-detr#221]
File”…/1ib/pvthon3,11/site-packages/torch/functional.py”, line 1335, in cdist
  return _VF.cdist(x1, x2, p, None) #type: ignore(attr-defined)
Runtimeprror: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA LAUNCH BLOCKING=1.
Compile with ‘TORCH_USE_CUDA_DSA’ to enable device-side assertions.

**Comment by SkalskiP** [comment]
@Wangwang99999 could you share the annotations file you're using? Just the JSON.

**Comment by Wangwang99999** [comment]
[_annotations.coco.json](https://github.com/user-attachments/files/20279150/_annotations.coco.json)
I modified line 47 in detr.py as:
class_names = [c["name"] for c in anns["categories"]]

**Comment by JackGUO-boy** [comment]
> [_annotations.coco.json](https://github.com/user-attachments/files/20279150/_annotations.coco.json) I modified line 47 in detr.py as: class_names = [c["name"] for c in anns["categories"]]

The ID for "categories" in my JSON starts from 0, and I have also modified the line of code in dert.py where class_name=[c ["name"] for c in anns ["categories"]]. However, when I run train.by, I still get an error: return _VF.cdist (x1, x2, p, None) # type: ignore [attr-defined]
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

How did you solve it?

**Comment by J7779** [comment]
@ThierryDeruyttere Thanks, that fixed the issue for me.

**Comment by Borda** [comment]
Hey — checking in on this one. Is this still an issue on the latest version (v1.6.1)? If so, let us know and we'll keep investigating. If not, we'll close this out to keep the tracker tidy. Feel free to reopen anytime if it resurfaces!
