### ISSUE TITLE
CUDA OOM during eval after epoch 0 on A100 (RFDETRSegSmall) at mask thresholding

### ISSUE THREAD

**Issue by Aasim-ComputerVision** [roboflow/rf-detr#646]
### Search before asking

- [x] I have searched the RF-DETR issues and found no similar bug report.

### Bug - CUDA OOM during evaluation after Epoch 0 on A100 80GB (RFDETRSegSmall Seg) — OOM at lwdetr.py:774 res_i['masks'] = masks_i > 0.0 (alloc 2.32 GiB) even with run_test=False / eval=False

Training of RFDETRSegSmall runs through Epoch 0 (2512 iters) successfully, then an evaluation phase labeled Test: starts and crashes with:

`torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.32 GiB`

The stack trace points to mask postprocessing:
```
rfdetr/models/lwdetr.py, line 774: res_i['masks'] = masks_i > 0.0

Despite passing run_test=False and (from printed args) eval=False, the evaluation still runs at the end of the epoch and triggers the OOM.
```
### Environment

Environment
GPU / Driver

From nvidia-smi:

GPU: NVIDIA A100-SXM4-80GB

Driver: 565.57.01

CUDA: 12.7

nvidia-smi snapshot (from the run) showed:

Memory usage: 72415 MiB / 81920 MiB

GPU-Util: 0%

Processes table: empty (this looked odd because memory was still reported as used)

Timestamp in that output:

Fri Feb 6 21:09:49 2026
Python

From stack paths:

Python 3.11 (/usr/local/lib/python3.11/dist-packages/...)

CPU / RAM

From top snapshot:

load average: 33.87, 37.98, 49.11

CPU: 13.6 us, 1.4 sy, 85.0 id (lots of idle CPU overall)

RAM: 1031853 MiB total, 67125 MiB free, 860969 MiB buff/cache

Swap: 0

Multiple pt_main_thread processes were active; one showed very high CPU% (e.g. 2523%), others ~19–22%.

### Minimal Reproducible Example
```py
model.train(
  dataset_dir=data_dir,
  output_dir=out_dir,
  epochs=20,
  batch_size=16,
  grad_accum_steps=2,
  amp=True,
  run_test=False,
  fp16_eval=True,
  eval_max_dets=100,
  do_benchmark=False,
  num_workers=12,
  early_stopping=False,
  tensorboard=True
)
```
### Additional

Also printed during training:

Grad accum steps: 2

Total batch size: 32

LENGTH OF DATA LOADER: 2512

![Image](https://github.com/user-attachments/assets/dcb9119e-0f9d-4734-88d3-3b415fa17673)

### Are you willing to submit a PR?

- [ ] Yes, I'd like to help by submitting a PR!

**Comment by isaacrob** [comment]
What's your image resolution?

**Comment by Aasim-ComputerVision** [comment]
My dataset images are high‑res and mixed: roughly 2K → 4K on disk (I’m not doing any offline resizing/rewriting of the dataset).

For training/eval/inference I’m using the built‑in RF-DETR resizing path (my understanding from the RF-DETR segmentation workflow is that it handles resizing internally), and the run’s printed config shows the model is operating at:

resolution=384 (this is also the resolution I intend to use at inference time)

square_resize_div_64=True

multi_scale=True / expanded_scales=True

Why i did this?
I’ve previously trained the segmentation preview using the same approach (dataset kept at original 2K–4K on disk, training at 384 via the pipeline), and it worked fine trained at 384 and handled the upsampling behavior correctly.

Why I think this is a bug in this release!

Even after setting what should make this OOM-safe:

run_test=False

early_stopping=False

fp16_eval=True

eval_max_dets=100

…the run still enters evaluation (Test: [0/513] ...) right after finishing Epoch 2, and then OOMs immediately at:

rfdetr/models/lwdetr.py:774
res_i['masks'] = masks_i > 0.0
(tries to allocate ~2.32 GiB, fails because GPU is already ~78–79 GiB used)

So it looks like eval-time mask postprocess is still upsampling to original image size (2K–4K) and then the boolean threshold forces an additional allocation and it happens even when run_test=False / eval=False are shown in the printed args.

Question: Is evaluation expected to always upsample masks back to original resolution for COCO eval? If yes, is there a way to:

keep eval masks at the fixed 384 resolution, or

chunk masks / process per-image/per-mask to avoid the large single allocation, or

move the boolean threshold / mask materialization to CPU?

Also: can you confirm which flag is supposed to fully disable evaluation during training for segmentation? Because from the logs, evaluation still runs and is the direct trigger for the OOM.

There are Two additional issues I’m seeing in this release (in case related)

Distributed / multi-GPU training
I’ve tried multiple times but only one GPU gets used. Logs show: “Not using distributed mode” with world_size=1, distributed=False.
Is DDP for segmentation supported in this branch? If yes, what is the exact recommended launcher/flags?

GPU utilization looks bursty / unstable
VRAM climbs and stays very high, but GPU utilization often drops to ~0% between bursts, which makes the run feel “stalled” at times (data time spikes are also visible in logs).

My current machine snapshot:

A100‑SXM4‑80GB

VRAM ~98% (reported as 84 GB / 86 GB)

Utilization 0% at snapshot (then bursts during steps)

Driver 570.195.03

OS Ubuntu 22.04.5 LTS

**Comment by ManuBN786** [comment]
I was facing the same issue with segmentation due to a bug in their mask prediction at original image size during evaluation on validation dataset. 

Setting run_test=False , run_valid=False didnt help as rfdetr runs eval on validation anyway.

So i resized my whole dataset to 1008 (divisible by 56) and the max resolution that bs=1 that can work on my gpu.

Now the training is working fine with no OOM at evaluation of validation dataset.

**Comment by isaacrob** [comment]
@Aasim-ComputerVision please open a different issue for DDP on windows. 

We always run validation during training. I highly recommend doing that because otherwise you risk overfitting. Therefore we have no feature to disable it. 

The OOM is because in order to compute mAP during validation we must upsample the masks to image resolution. This is not a bug @ManuBN786, this is required behavior for proper calculation of mAP. 

The solution is what @ManuBN786 suggested, which is to downsize your dataset. This will probably also help with the 'bursting' you're seeing as right now you're loading 4k images just to immediately down sample them to 384. We use an optimized version of the PointRend loss for segmentation which CAN benefit from using very high resolution masks during training from your high resolution dataset, but in practice the benefit is likely small. 

Finally, you can always reduce memory by using more grad accumulate steps with a lower local batch size while keeping total batch size constant. RF-DETR uses layernorm instead of batchnorm to help ensure stability at low local batch sizes, enabling the use of gradient accumulation.

**Comment by Borda** [comment]
Hi @Aasim-ComputerVision — apologies for not circling back on this sooner. As @isaacrob explained, validation mask upsampling to original image resolution is required for accurate mAP — this is by design rather than a bug. v1.6.0 introduced PTL-based training, which gives you better control over evaluation, and #851 (lazy mask materialization, merged to develop, coming in the next release) should further reduce peak memory for large datasets. For now, downsizing source images (as @ManuBN786 suggested) remains the recommended approach. Closing this — please reopen if you still see unexpected behavior on v1.6.1.
